### ISSUE TITLE
Check instead of fix?

### ISSUE THREAD

**Issue by garak** [OskarStark/php-cs-fixer-ga#111]
I recently noticed that this action fixes my files instead of checking them, so it never fails.
Example of log:

```

Run docker://oskarstark/php-cs-fixer-ga
/usr/bin/docker run --name oskarstarkphpcsfixerga_9566d6 --label 495d9b --workdir /github/workspace --rm -e "APP_DATABASE_URL" -e "APP_DEBUG" -e "APP_ENV" -e "APP_MAILER_DSN" -e "APP_SECRET" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ecmsuite_reloaded/ecmsuite_reloaded":"/github/workspace" oskarstark/php-cs-fixer-ga
PHP CS Fixer 3.64.0 (209f776) Space Sets by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.3.12
PHP CS Fixer 3.64.0 (209f776) Space Sets by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.3.12
Running analysis on 1 core sequentially.
You can enable parallel runner and speed up the analysis! Please see https://cs.symfony.com/doc/usage.html for more information.
Loaded config default from "/github/workspace/.php-cs-fixer.php".
   0/381 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  39/381 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%
  77/381 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20%
 115/381 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30%
 153/381 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%
 191/381 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%
 229/381 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  60%
 267/381 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  70%
 305/381 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  80%
 343/381 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  90%
 381/381 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

   1) [redacted].php
   2) [redacted].php
   3) [redacted].php
   4) [redacted].php

Fixed 4 of 381 files in 3.892 seconds, 21.08 MB memory used
```

This is my config:

```
jobs:
                  XDEBUG_MODE=off bin/phpstan
    cs-fixer:
        runs-on: ubuntu-24.04
        name: PHP-CS-Fixer
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Fix CS
              uses: docker://oskarstark/php-cs-fixer-ga
```

Did I do someting wrong?

**Comment by Sparknsk** [comment]
@garak `check` command it is alias for `fix --dry-run` so you can try to modify your config like that
```
jobs:
    cs-fixer:
        runs-on: ubuntu-24.04
        name: PHP-CS-Fixer
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Fix CS
              uses: docker://oskarstark/php-cs-fixer-ga`
              with:
                args: --dry-run
```
