### ISSUE TITLE
##[error]Docker run failed with exit code 1

### ISSUE THREAD

**Issue by w3bdesign** [OskarStark/php-cs-fixer-ga#13]
I am getting the following when trying to run the fixer for the first time:
 
```
PHP-CS-Fixer
5s
##[error]Docker run failed with exit code 1
Run docker://oskarstark/php-cs-fixer-ga
/usr/bin/docker run --name oskarstarkphpcsfixerga_490539 --label 10865d --workdir /github/workspace --rm -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/Bootstrap-App-PHP-MVC/Bootstrap-App-PHP-MVC":"/github/workspace" oskarstark/php-cs-fixer-ga
Loaded config default.

In Finder.php line 569:
                                                                               
  **You must call one of in() or append() methods before iterating over a Finde  
  r.**     
```

**Comment by w3bdesign** [comment]
My main.yml:

```
on: [push, pull_request]
name: MVCMainflow
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
```
