### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Nyholm** [OskarStark/php-cs-fixer-ga#17]
I want to share something I just learnt. 

Looking at [Github actions docs](https://help.github.com/en/actions/building-actions/about-actions#versioning-your-action) and the [actions/checkout action](https://github.com/actions/checkout/releases), we can see that one should move tags. 

Ie, create tags as we (PHP community) usually do. But also move the `v2` tag with the latest release. 

The benefit is that I (as a consumer of the action) can use `OskarStark/php-cs-fixer-ga@v2` the same way as we use composers: `^2.0` syntax. 

Im not sure that this is something we would like do to or if it is necessary. Since the updates here are just following releases of php-cs-fixer. I think it is easier for if one just did: 

```yaml
      - name: PHP-CS-Fixer
        uses: OskarStark/php-cs-fixer-ga@master
        with:
          args: --dry-run --diff-format udiff
```
