### ISSUE TITLE
actually fix cs via github action

### ISSUE THREAD

**Issue by clxmstaab** [OskarStark/php-cs-fixer-ga#5]
would it be possible to actually fix the codestyling using php-cs-fixer with this action (e.g. by typing a certain command via a comment or similar)?

**Comment by OskarStark** [comment]
Not yet but you can run the docker command locally from the readme to fix the issues, so that you don’t need that dependency in your composer.json file

**Comment by staabm** [comment]
after using some other Github Actions as a 'end-user' it seems to me that a comment triggered action command would be best for this.

something like: when a comment is posted to a pull request which contains `/fix-cs` let the action run, fix the code and push to this pull request.

inspiration can be taken from https://github.com/cirrus-actions/rebase which does that with a different command.

I have no experience with docker or authoring github actions, therefore won't tackle it myself in the next weeks/months though.

**Comment by OskarStark** [comment]
Nice idea

**Comment by staabm** [comment]
I guess this would be easy to achieve using https://github.com/peter-evans/create-pull-request

**Comment by OskarStark** [comment]
Nice idea

**Comment by mpdude** [comment]
Let's give it a try:

```yml
on: [push]
name: Create PRs for php-cs-fixer fixups

jobs:
    fix-cs:
        name: Fix CS violations
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: docker://oskarstark/php-cs-fixer-ga:latest
            - uses: peter-evans/create-pull-request@v2
              id: cpr
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: Apply php-cs-fixer changes as of ${{ github.sha }}
                  title: Fix coding standards in ${{ github.ref }}
                  branch: php-cs-fixer/${{ github.ref }}
                  assignees: ${{ github.actor }}
                  body: |
                    Please apply these changes on the ${{ github.ref }} branch to fix coding standard violations.

            - uses: unsplash/comment-on-pr@v1.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: steps.cpr.outputs.pr_number
              continue-on-error: true # Will fail if not on PR
              with:
                  msg: |
                    @${{ github.actor }} please apply the coding standard fixes from #${{ steps.cpr.outputs.pr_number }}
```

This will monitor all pushed commits. Whenever a commit violates CS, 
* create a branch named `php-cs-fixer/` + the name of the branch with the bogus commits
* (force) push necessary changes there
* Open a PR, to merge that branch into the offending branch
* If the offending branch has a corresponding PR open, add a comment in it to point to the fixups

Only downside: If a branch or PR violates CS, the status checks will be green, regardless of whether a fix is necessary or not.
